-- Project : E-commerce Analysis Using SQL
-- Author  : Saurabh Gopal Chaudhari

--   Ecommerce Analysis and Customer Analysis

CREATE DATABASE ecommerce_analysis;

USE ecommerce_analysis;

CREATE TABLE customers(
	customer_id INT PRIMARY KEY,
	country VARCHAR(50),
	signup_date DATE
);

CREATE TABLE products(
	product_id INT PRIMARY KEY,
	product_name VARCHAR(100),
	category VARCHAR(50)
);

CREATE TABLE orders(
	order_id INT PRIMARY KEY,
	customer_id INT,
	order_date DATE,
	status VARCHAR(20),
	FOREIGN KEY(customer_id)
	REFERENCES customers(customer_id)
);

CREATE TABLE order_items(
	order_item_id INT PRIMARY KEY AUTO_INCREMENT,
	order_id INT,
	product_id INT,
	quantity INT,
	price DECIMAL(10,2),

	FOREIGN KEY(order_id)
	REFERENCES orders(order_id),

	FOREIGN KEY(product_id)
	REFERENCES products(product_id)
);

-- Retrieve all cancelled orders.

SELECT *
FROM orders
WHERE status = 'Cancelled';


-- Retrieve all unique customer countries.

SELECT DISTINCT country
FROM customers;


-- Retrieve all unique product categories.

SELECT DISTINCT category
FROM products;


-- Display orders placed after a specific date.

SELECT *
FROM orders
WHERE order_date > '2024-06-01'
ORDER BY order_date DESC;


-- Count total rows in each table.

SELECT COUNT(*) AS total_customers
FROM customers;

SELECT COUNT(*) AS total_orders
FROM orders;

SELECT COUNT(*) AS total_order_items
FROM order_items;

SELECT COUNT(*) AS total_products
FROM products;


-- Display the top unique 10 highest prices.

SELECT DISTINCT price
FROM order_items
ORDER BY price DESC
LIMIT 10;


-- Calculate total orders by status.

SELECT
    status,
    COUNT(*) AS total_orders
FROM orders
GROUP BY status;


-- Calculate total quantity sold per product.

SELECT
    product_id,
    SUM(quantity) AS total_quantity_sold
FROM order_items
GROUP BY product_id;


-- Calculate order count for each customer.

SELECT
    customer_id,
    COUNT(*) AS total_orders
FROM orders
GROUP BY customer_id;


-- Identify customers with multiple orders.

SELECT
    customer_id,
    COUNT(*) AS total_orders
FROM orders
GROUP BY customer_id
HAVING COUNT(*) > 1;


-- Generate a month-wise order summary.

SELECT
    YEAR(order_date) AS order_year,
    MONTHNAME(order_date) AS order_month,
    COUNT(*) AS total_orders
FROM orders
GROUP BY
    YEAR(order_date),
    MONTH(order_date),
    MONTHNAME(order_date)
ORDER BY
    order_year,
    MONTH(order_date);


-- Count orphan orders.

SELECT COUNT(*) AS orphan_orders
FROM orders
WHERE order_id NOT IN
(
    SELECT order_id
    FROM order_items
);


-- Retrieve every order together with
-- the customer's country.

SELECT
    o.order_id,
    c.country
FROM orders o
INNER JOIN customers c
        ON o.customer_id = c.customer_id;


-- Calculate revenue generated by each order.

SELECT
    oi.order_id,
    SUM(oi.quantity * oi.price) AS total_revenue
FROM order_items oi
GROUP BY oi.order_id;


-- Calculate total revenue for each category.

SELECT
    p.category,
    SUM(oi.quantity * oi.price) AS total_revenue
FROM products p
INNER JOIN order_items oi
        ON p.product_id = oi.product_id
GROUP BY p.category
ORDER BY total_revenue DESC;


-- Calculate total revenue generated by each country.

SELECT
    c.country,
    SUM(oi.quantity * oi.price) AS total_revenue
FROM customers c
INNER JOIN orders o
        ON c.customer_id = o.customer_id
INNER JOIN order_items oi
        ON o.order_id = oi.order_id
GROUP BY c.country
ORDER BY total_revenue DESC;


-- Identify orders having no order items.

SELECT
    o.*
FROM orders o
LEFT JOIN order_items oi
       ON o.order_id = oi.order_id
WHERE oi.order_id IS NULL;


-- Retrieve the top customers by revenue.

SELECT
    c.customer_id,
    SUM(oi.quantity * oi.price) AS total_revenue
FROM customers c
INNER JOIN orders o
        ON c.customer_id = o.customer_id
INNER JOIN order_items oi
        ON o.order_id = oi.order_id
GROUP BY c.customer_id
ORDER BY total_revenue DESC
LIMIT 10;


-- Classify orders into High Value and Low Value.

SELECT
    order_id,
    SUM(quantity * price) AS revenue,
    CASE
        WHEN SUM(quantity * price) > 500
             THEN 'High Value'
        ELSE 'Low Value'
    END AS order_segment
FROM order_items
GROUP BY order_id;


-- Generate a pivot-style summary of order statuses.

SELECT
    SUM(CASE WHEN status='Completed' THEN 1 ELSE 0 END)
        AS completed_orders,

    SUM(CASE WHEN status='Cancelled' THEN 1 ELSE 0 END)
        AS cancelled_orders,

    SUM(CASE WHEN status='Returned' THEN 1 ELSE 0 END)
        AS returned_orders
FROM orders;


-- Calculate cancellation rate.

SELECT
ROUND
(
(
    SELECT COUNT(*)
    FROM orders
    WHERE status = 'Cancelled'
)
*100.0/
(
    SELECT COUNT(*)
    FROM orders
),
2
) AS cancellation_rate;


-- Calculate Average Order Value.

SELECT
ROUND
(
(
    SELECT SUM(quantity * price)
    FROM order_items
)
/
(
    SELECT COUNT(DISTINCT order_id)
    FROM orders
),
2
) AS average_order_value;


-- Find customers having zero orders.

SELECT
    c.customer_id,
    c.country
FROM customers c
WHERE NOT EXISTS
(
    SELECT 1
    FROM orders o
    WHERE o.customer_id = c.customer_id
);


-- Determine which category has the
-- highest cancellation rate.

SELECT
    p.category,
    ROUND(
        COUNT(
            CASE
                WHEN o.status = 'Cancelled'
                THEN 1
            END
        ) * 100.0 / COUNT(*),
        2
    ) AS cancellation_rate
FROM products p
JOIN order_items oi
    ON p.product_id = oi.product_id
JOIN orders o
    ON oi.order_id = o.order_id
GROUP BY p.category
ORDER BY cancellation_rate DESC
LIMIT 1;

-- ==========================================================
-- Reusable CTE : Customer Spending
-- ==========================================================

WITH customer_spend AS
(
    SELECT
        o.customer_id,
        SUM(oi.quantity * oi.price) AS total_spend
    FROM orders o
    INNER JOIN order_items oi
            ON o.order_id = oi.order_id
    GROUP BY o.customer_id
)

-- Customers spending above average.

SELECT *
FROM customer_spend
WHERE total_spend >
(
    SELECT AVG(total_spend)
    FROM customer_spend
);

-- Customers spending more than 1000.

SELECT *
FROM customer_spend
WHERE total_spend > 1000;


-- Identify repeat customers.

WITH repeat_customers AS
(
    SELECT
        customer_id,
        COUNT(*) AS total_orders
    FROM orders
    GROUP BY customer_id
    HAVING COUNT(*) > 1
)

SELECT
    r.customer_id,
    c.country,
    r.total_orders
FROM repeat_customers r
INNER JOIN customers c
        ON r.customer_id = c.customer_id;


-- ==========================================================
-- Reusable CTE : Monthly Revenue
-- ==========================================================

WITH monthly_revenue AS
(
    SELECT
        DATE_FORMAT(o.order_date,'%Y-%m') AS order_month,
        SUM(oi.quantity * oi.price) AS revenue
    FROM orders o
    INNER JOIN order_items oi
            ON o.order_id = oi.order_id
    GROUP BY DATE_FORMAT(o.order_date,'%Y-%m')
)

-- Calculate Month-over-Month Growth.

SELECT
    order_month,
    revenue,
    LAG(revenue)
        OVER(ORDER BY order_month)
        AS previous_month_revenue,

    ROUND
    (
        (
            revenue -
            LAG(revenue)
                OVER(ORDER BY order_month)
        ) * 100.0
        /
        LAG(revenue)
            OVER(ORDER BY order_month),
        2
    ) AS mom_growth_percentage
FROM monthly_revenue;


-- Calculate cumulative revenue.

SELECT
    order_month,
    revenue,

    SUM(revenue)
    OVER
    (
        ORDER BY order_month
        ROWS BETWEEN
        UNBOUNDED PRECEDING
        AND CURRENT ROW
    ) AS running_revenue
FROM monthly_revenue;


-- Rank customers based on revenue.

SELECT
    o.customer_id,
    SUM(oi.quantity * oi.price) AS total_revenue,

    RANK() OVER
    (
        ORDER BY
        SUM(oi.quantity * oi.price) DESC
    ) AS revenue_rank
FROM orders o
INNER JOIN order_items oi
        ON o.order_id = oi.order_id
GROUP BY o.customer_id;


-- Identify the highest revenue order
-- for each country.

WITH country_orders AS
(
    SELECT
        c.country,
        o.order_id,
        SUM(oi.quantity * oi.price) AS total_revenue,

        ROW_NUMBER() OVER
        (
            PARTITION BY c.country
            ORDER BY
            SUM(oi.quantity * oi.price) DESC
        ) AS country_rank

    FROM customers c
    INNER JOIN orders o
            ON c.customer_id = o.customer_id
    INNER JOIN order_items oi
            ON o.order_id = oi.order_id
    GROUP BY
        c.country,
        o.order_id
)

SELECT
    country,
    order_id,
    total_revenue
FROM country_orders
WHERE country_rank = 1;